FROM python:3.11.9-slim

WORKDIR /app

# Copy all project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Download TextBlob corpora (your project uses it)
RUN python -m textblob.download_corpora

# Expose port 7860 (Hugging Face default)
EXPOSE 7860

# Run Flask app
CMD ["python", "app.py"]